### ISSUE TITLE
ToggleDevice is not Working

### ISSUE THREAD

**Issue by daniel-scatigno** [kattunga/BlazorZXingJs#1]
I've created a Reference for the component, and on button click I'm calling ToggleDevice()
but it's not working

`           <div>
              <button class="btn btn-light" @onclick='()=>
                 {
                  QrReader.ToggleDevice();
                  Console.WriteLine("Togle Device");
                 }'><i class="fas fa-refresh"></i>Mudar Camera</button>
           </div>
            <MultiFormatReader style="width:100%" VideoHeigth="300" OnBarcodeRead="((args)=> BarcodeRead(args,AViewModel,DialogService))" @ref="QrReader" >
               <VideoForbidden>
                  <h4>É necessário conceder permissão de visualização da câmera</h4>
               </VideoForbidden>
               <NoVideoDevices>
                  <h4>Nenhum despositivo de video disponível</h4>
               </NoVideoDevices>
            </MultiFormatReader>`

Nothing happens when ToggleDevice is called, if I try to StopDecoding before calling ToggleDevice
no video is shown after the call. Which gives me the impression that the library is not finding more than one device (Judging by the code of method ToggleDevice)

It would be nice to expose the list of founded Devices, since we have Cellphones with 5 cameras. This way the user could select the device in an DropDownList

**Comment by daniel-scatigno** [comment]
I've checked now that the Demo folder contains an example retrieving the List of Devices through the event OnStartVideo

I've pasted the example page into my project, but the problem remains.
When it's started, the list of devices is blank, if I change the format video, the list is refreshed, but when I select another device, no vide is outputed.

**Comment by kattunga** [comment]
Hello, please provide more information,

Nuget version?
Dotnet Version?
Blazor model: server / wasm / wasm pwa
Web browser: Firefox / Chrome
Client OS: Windows / Linux / IOS / Android

Regards

**Comment by daniel-scatigno** [comment]
Hi, 
Nuget version: 0.4.3
Dotnet Version:  5.0
Blazor model:  Wasm 
Web browser: Chrome 88 / Microsoft Edge
Client OS: Windows 10

**Comment by kattunga** [comment]
I will try similar environment.
Did you test the demo as it is and you see the bug?

**Comment by kattunga** [comment]
Please, check server version too, PWA aggressively cache resources and you may still viewing a bug from previous version.

**Comment by daniel-scatigno** [comment]
I've tried the Demo. The main difference is that it does load devices (Show List) 
but changing the device still a problem, I get a no permission for videodevice when I hit the toggle button.

**Comment by kattunga** [comment]
Please check latest commit or release 0.4.4

**Comment by daniel-scatigno** [comment]
Hi, I cleared the cache and tested it running the Demo, but the problem remains. 
Weather I click on toggle button it does appear No Permission issue. If I refresh the page the toggle button works just Once. 

I've checked the Script that access Zxing library, I would like to suggest some changes.
The script is only loading (Getting the list) the devices when It starts to decode the camera. I think a better approach would be to retrieve the list first, store values just once. And when the toggle button is pressed cycle between then, stopping the decode and starting it again.

**Comment by kattunga** [comment]
You can't retrieve list first because list it is not available until the user give permission to camera, and permission is asked when you start to decode.

Did you get latest commit?, take care that I fixed a bug in demo too.

**Comment by kattunga** [comment]
Please check developer console in chrome, the right error message is logged there.

**Comment by kattunga** [comment]
Please check version 0.5.0, I made a rework of error handling

**Comment by daniel-scatigno** [comment]
Hi, sorry for the Delay, I can confirm that Toggle Button is now working as expected!
Thanks a lot
