### ISSUE TITLE
Offline capable use of the library

### ISSUE THREAD

**Issue by thepra** [kattunga/BlazorZXingJs#4]
This piece of code breaks everything when it comes to qr code scanning when the client is offline:
![immagine](https://user-images.githubusercontent.com/7032509/138518920-113fd210-461e-41ae-a278-4f0015342880.png)

Could you remove the dynamic loading of that library and make the loading of that library normal?

This isn't the first library optimizing the loading of js modules like this but the worst side effect is DI breaking and a totally capable app that could continue to work offline suddenly becomes unreliable offline.

**Comment by claudiopizzillo** [comment]
To avoid this, use my escamotage in wasm with PWA :
```
    <script src="_content/BlazorZXingJs/MultiFormatReader.js" type="module"></script>
    <script src="_content/BlazorZXingJs/QRCodeWriter.js" type="module"></script>
    <script>navigator.serviceWorker.register('service-worker.js');</script>
```
